### ISSUE TITLE
Never returns when run more than once.

### ISSUE THREAD

**Issue by scott-phillips-sp** [AceMetrix/bower-license#15]
The problem is that the completed variable is never reset between runs.

**Comment by scott-phillips-sp** [comment]
To get around this problem, I am forcing the module to be reloaded between runs:

delete require.cache[__dirname+'/node_modules/bower-license/lib/index.js'];
var bowerChecker = require('bower-license');

**Comment by badunk** [comment]
ah I see, working on a fix

**Comment by badunk** [comment]
Can you try version 0.4.1?

**Comment by scott-phillips-sp** [comment]
Yup, works perfect. 

Thank you for the update.
