### ISSUE TITLE
indexOf is not a function

### ISSUE THREAD

**Issue by bfabec** [AceMetrix/bower-license#20]
Getting the following error when using bower-license against fullcalendar. 
https://github.com/fullcalendar/fullcalendar

With the following license:
[{"type":"MIT","url":"https://github.com/fullcalendar/fullcalendar/blob/master/LICENSE.txt"}]

I was able to workaround by updating line 68 of index.js:
var iAsk = license.indexOf('*');
to
var iAsk =  license.indexOf ? license.indexOf('*') : -1; 

Stack:
Z:\workspace_anaas_rto\Alert Notification Bluemix Software\src\node_modules\bower-license\lib\index.js:69
                            var iAsk =  license.indexOf('*');
                                                ^

TypeError: license.indexOf is not a function
    at Z:\workspace_anaas_rto\Alert Notification Bluemix Software\src\node_modules\bower-license\lib\index.js:69:49
    at Array.filter (native)
    at Function._.filter._.select (Z:\workspace_anaas_rto\Alert Notification Bluemix Software\src\node_modules\bower-license\node_modules\underscore\underscore.js:172:65)
    at Z:\workspace_anaas_rto\Alert Notification Bluemix Software\src\node_modules\bower-license\lib\index.js:68:49
    at Z:\workspace_anaas_rto\Alert Notification Bluemix Software\src\node_modules\bower-license\node_modules\npm-license\lib\index.js:134:9
    at Z:\workspace_anaas_rto\Alert Notification Bluemix Software\src\node_modules\bower-license\node_modules\npm-license\node_modules\read-installed\read-installed.js:142:5
    at Z:\workspace_anaas_rto\Alert Notification Bluemix Software\src\node_modules\bower-license\node_modules\npm-license\node_modules\read-installed\read-installed.js:263:14
    at asyncMap (Z:\workspace_anaas_rto\Alert Notification Bluemix Software\src\node_modules\bower-license\node_modules\npm-license\node_modules\read-installed\node_modules\slide\lib\async-map.js:27:18)
    at next (Z:\workspace_anaas_rto\Alert Notification Bluemix Software\src\node_modules\bower-license\node_modules\npm-license\node_modules\read-installed\read-installed.js:234:5)
    at Z:\workspace_anaas_rto\Alert Notification Bluemix Software\src\node_modules\bower-license\node_modules\npm-license\node_modules\read-installed\read-installed.js:179:7

**Comment by badunk** [comment]
Ah I see

I'm on the side that if the package.json isn't correct (https://docs.npmjs.com/files/package.json), it shouldn't attempt to infer it w/ all the various ways authors are publishing it.

In any case, it shouldn't fail hard, however.  Let me look into this

**Comment by badunk** [comment]
thanks!
